"""Constants for kintone MCP server."""

# API Limits
MAX_RECORDS_PER_REQUEST = 500
MAX_APPS_PER_REQUEST = 100
MAX_BATCH_RECORDS = 100
MAX_COMMENTS_PER_REQUEST = 10
MAX_FILE_SIZE = 1024 * 1024 * 100  # 100MB
MAX_OFFSET = 10000

# Default values
DEFAULT_DOMAIN = "cybozu.com"
DEFAULT_RECORD_LIMIT = 100
DEFAULT_APP_LIMIT = 100
DEFAULT_COMMENT_LIMIT = 10

# Request timeout
DEFAULT_TIMEOUT = 30
FILE_UPLOAD_TIMEOUT = 300

# Rate limiting
MAX_REQUESTS_PER_MINUTE = 100
RATE_LIMIT_WINDOW = 60  # seconds

# File paths
TEMP_FILE_PREFIX = "kintone_temp_"

# Auth types
AUTH_TYPE_API_TOKEN = "api_token"
AUTH_TYPE_PASSWORD = "password"

# Headers
HEADER_API_TOKEN = "X-Cybozu-API-Token"
HEADER_AUTH = "X-Cybozu-Authorization"
HEADER_CONTENT_TYPE = "Content-Type"
HEADER_METHOD_OVERRIDE = "X-HTTP-Method-Override"

# Content types
CONTENT_TYPE_JSON = "application/json"
CONTENT_TYPE_MULTIPART = "multipart/form-data"

# Error codes
ERROR_RATE_LIMIT = "RATE_LIMIT_EXCEEDED"
ERROR_AUTH_FAILED = "AUTH_FAILED"
ERROR_INVALID_REQUEST = "INVALID_REQUEST"
ERROR_PERMISSION_DENIED = "PERMISSION_DENIED"
